apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow
  labels:
    app: kubeflow
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1