apiVersion: v1
kind: ConfigMap
metadata:
  name: php-conf
data:
  php-fpm.conf: |
    [global]
    daemonize = no
    error_log = /dev/stderr
    log_level = warning
    [app]
    listen = 0.0.0.0:9000
    access.log = /dev/stdout
    user = app
    group = app
    pm = static
    pm.max_children = 1
    catch_workers_output = yes
    clear_env = no
    ping.path = /ping
    pm.status_path = /status
    slowlog = /dev/stderr
    catch_workers_output = yes
    php_admin_value[error_log] = /dev/stderr
    php_admin_flag[log_errors] = on
    env[HOSTNAME] = $HOSTNAME
    env[TMP] = /tmp
    env[TMPDIR] = /tmp
    env[TEMP] = /tmp
  php.ini: |
    date.timezone=UTC
    memory_limit = -1
    error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    upload_max_filesize = 20M
    post_max_size = 20M
    log_errors_max_len = 8192
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      log_format json_http_combined escape=json
          '{ "@timestamp":"$time_iso8601",'
            '"server_name":"$server_name",'
            '"status":$status,'
            '"bytes_sent":$bytes_sent,'
            '"body_bytes_sent":$body_bytes_sent,'
            '"remote_addr":"$remote_addr",'
            '"request_time":$request_time,'
            '"request_id":"$request_id",'
            '"request_length":$request_length,'
            '"request_method":"$request_method",'
            '"request_uri":"$request_uri", '
            '"request_path":"$uri", '
            '"request_param":"$query_string", '
            '"request_body":"$request_body", '
            '"server_addr":"$server_addr",'
            '"server_port":$server_port,'
            '"server_protocol":"$server_protocol",'
            '"ssl_protocol":"$ssl_protocol",'
            '"ssl_cipher":"$ssl_cipher",'
            '"ssl_session_id":"$ssl_session_id",'
            '"http_host":"$http_host",'
            '"http_referrer":"$http_referer",'
            '"http_user_agent":"$http_user_agent",'
            '"http_x_forwarded_for:"$http_x_forwarded_for",'
            '"upstream_addr":"$upstream_addr",'
            '"upstream_response_time":$upstream_response_time,'
            '"upstream_connect_time":$upstream_connect_time }';
      access_log /dev/stdout json_http_combined;
      error_log /dev/stdout;
      include /etc/nginx/virtualhost.conf;
    }
  virtualhost.conf: |
    map $http_user_agent $logger {
     default 1;
     "~kube-probe" 0;
    }
    server {
      listen 80 default_server;
      server_name _;
      root /app/public;
      access_log /dev/stdout json_http_combined if=$logger;
      error_log /dev/stdout;
      index index.php;
      location / {
          try_files $uri /index.php$is_args$args;
      }
      location ~ \.php {
          try_files $uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param SCRIPT_NAME $fastcgi_script_name;
          fastcgi_index index.php;
          fastcgi_pass 127.0.0.1:9000;
      }
    }